version: 2

jobs:
  build:
    working_directory: /tmp/compile/project1
    docker:
      - image: node:10.15

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          name: Linting and checking formatting
          command: |
            npm run lint
            npm run fmt:check

      - run:
          name: Run tests
          command: npm run test:ci

      - run:
          name: Build project
          command: npm run build
